config/routes.rb
FastLearningCompany::Application.routes.draw do

  root                            to: 'static_pages#home'

  match '/home',                  to: 'static_pages#home'  
  match '/about',                 to: 'static_pages#about' 
  match '/calendar',              to: 'static_pages#calendar' 
  match '/terms',                 to: 'static_pages#terms' 
  match '/contact',               to: 'static_pages#contact' 

  resources :courses  
  resources :classrooms, except: [:show] do
    match ':id(.:format)',  to: 'classrooms#show', as: :page, via: :get
  end

  resources :learning_plans
  resources :products
  resources :orders

  resources  :checkout

  resources :enrollments
  
  resources :sessions, only: [:new, :create, :destroy]
  
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/profile', to: 'users#show'
  
  resources :passwords
  
  resources :pages

  resources :resources
  

  resources :companies, :path => '', :path_names => { :edit => 'account' } 
  resources :companies, :path => '', :only => [], :shallow => true do 
    resources :learners, :path => 'people', :path_names => { :edit => 'account',  :new => 'new' } 
  end

  match '*a', :to => 'errors#routing'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def calendar
  end

  def terms
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide( :title , 'Om Fastlearning Company') %>
<h4>Om Fastlearning Company</h4>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/calendar.html.erb
<% provide( :title , 'Kalender') %>
<h4>Kalender</h4>
<p>Find me in app/views/static_pages/calendar.html.erb</p>

app/views/static_pages/contact.html.erb
<% provide( :title, 'Kontakt' ) %>
<h4>Kontakt</h4>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/home.html.erb
<h4>Forside</h4>
<p>Find me in app/views/static_pages/home.html.erb</p>
<li><%= link_to "New asset",  new_resource_path %></li>

app/views/static_pages/terms.html.erb
<% provide( :title, 'Vilkår' ) %>
<h4>Vilkår</h4>
<p>Find me in app/views/static_pages/terms.html.erb</p>