config/routes.rb
FastLearningCompany::Application.routes.draw do

  root                            to: 'static_pages#home'

  match '/home',                  to: 'static_pages#home'  
  match '/about',                 to: 'static_pages#about' 
  match '/calendar',              to: 'static_pages#calendar' 
  match '/terms',                 to: 'static_pages#terms' 
  match '/contact',               to: 'static_pages#contact' 

  resources :courses  
  resources :classrooms, except: [:show] do
    match ':id(.:format)',  to: 'classrooms#show', as: :page, via: :get
  end

  resources :learning_plans
  resources :products
  resources :orders

  resources  :checkout

  resources :enrollments
  
  resources :sessions, only: [:new, :create, :destroy]
  
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/profile', to: 'users#show'
  
  resources :passwords
  
  resources :pages

  resources :resources
  

  resources :companies, :path => '', :path_names => { :edit => 'account' } 
  resources :companies, :path => '', :only => [], :shallow => true do 
    resources :learners, :path => 'people', :path_names => { :edit => 'account',  :new => 'new' } 
  end

  match '*a', :to => 'errors#routing'

end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_secure_password  
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  # Accesible
  attr_accessible :name, :email, :password, :password_confirmation, :avatar
  
  # Callbacks
  before_create   :create_id_hash
  before_save     :downcase_email
  before_save     :fix_name
  before_save     { generate_token( :remember_token ) }
  
  # Validations
  validates       :name, presence: true, length: { maximum: 50 }  
  validates       :email, presence:   true,
                  format:     { with: VALID_EMAIL_REGEX },
                  uniqueness: { case_sensitive: false }
  
  validates       :password, presence: true, length: { minimum: 6 }, 
                  :if => lambda{ new_record?  || !password.nil? && !password.empty?  }
                  
  validates       :password_confirmation, presence: true,
                  :if => lambda{ !password.nil? && !password.empty? }

  # Paperclip
  has_attached_file :avatar, 
                    :styles => { :medium => "140x140>", :thumb => "35x35>" },
                    :default_url => '/assets/avatars/default_:style.png',
                    :path => "/avatars/:style/:id/:filename",
                    :s3_permissions => :public_read

  ##############################################################
  # Public interface
  ##############################################################

  def send_password_reset
    generate_token( :reset_password_token )
    self.reset_password_sent_at = Time.zone.now
    save!
    UserMailer.password_reset( self ).deliver
  end
  
  def role?( role )
    return role.to_s.camelize == self.type
  end
  
  def status?( status )
    return status.to_s == self.status
  end

  
  def to_param
    id_hash
  end

  def increment_sign_in_count
    self.sign_in_count += 1
    self.save!
  end

  #def self.inherited(child)
  #  child.instance_eval do
  #    def model_name
  #      User.model_name
  #    end
  #  end
  # super
  #end

  ##############################################################
  # Private interface
  ##############################################################
  private
  
  def generate_token( column )
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?( column => self[column] )
  end
  
  def create_id_hash
    self.id_hash = Digest::SHA2.hexdigest( self.email )[0..6]
  end

  
  def set_status( status )
    self.status = status
  end

  
  def downcase_email
    self.email = self.email.downcase
  end

  def fix_name
    self.name = construct_name( self.name.split )
  end
  
  def construct_name( name )
    if name.length == 0
      return ""
    elsif name.length == 1
      return name.shift.capitalize
    else
      name.shift.capitalize + " " + construct_name( name )
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  respond_to :html, :xml, :json
  load_and_authorize_resource :find_by => :id_hash

  def index
  end

  def show
  end
    
  def new
  end
  
  def create
  end
  
  def edit
  end

  def update
  end
  
  def destroy
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<% provide(:title, 'Rediger profil') %>
<%= render 'shared/error_messages' %>    
<%= form_for(@user, :html => {  :multipart => true, :class => "new_user"}) do |f| %>
  <%= image_tag @user.avatar.url( :medium ) %>
  <div class="clear"></div>
  <%= f.file_field :avatar %>
  <%= render :partial => 'shared/basic_user_info', :locals => { :f => f } %>  
  <div><%= f.submit "Gem ændringer", class: 'btn' %></div>
<% end %>

app/views/users/show.html.erb
<% provide(:title, current_user.name) %>
<% if current_user.role? :learner %>
<div class="cl-header cl-header-inner">
  <h3 class="alt">Læringsrum</h3>
</div>

  <% current_user.enrollments.each do |enrollment| %>
  <% if enrollment.status == 'enrolled' %>    
    <%= link_to [enrollment.classroom, enrollment.classroom.pages.where("title = 'Forside'").first] do %> 
      <div class="classrooms thumb L">
	<div class="ribbon-wrapper">
	  <div class="ribbon" style="background-color: <%= enrollment.classroom.course.color %>"><%= enrollment.classroom.online_date.strftime("%d %b %y") %></div>
	</div>
	<div class="thumb-inner L">
	  <h3 class="alt"><div><%= enrollment.classroom.course.title %></div></h3>
	  <h4 class="alt">Du er tilmeldt dette læringsrum</h4>
	</div>
      </div>  
    <% end %>
  <% else %>
    <%= link_to edit_enrollment_path( enrollment ) do %> 
      <div class="classrooms thumb L">
	<div class="ribbon-wrapper">
	  <div class="ribbon" style="background-color: #878787">Inviteret</div>
	</div>
	<div class="thumb-inner L">
	  <h3 class="alt"><div><%= enrollment.course.title %></div></h3>
	  <h4 class="alt">Du er tilmeldt dette læringsrum</h4>
	</div>
      </div>
    <% end %>
  <% end %>
<% end %>
<% end %>

  <div class="clear"></div>    

<% if current_user.role? :company %>
<div class="cl-header cl-header-inner">
  <h3 class="alt">Medarbejdere</h3>
</div>
<div class="row">
  <div class="span2">  
    <%= link_to new_user_learner_path( current_user ) do %>
    <button class="btn btn-success btn-mini pad-button"><i class="icon-white icon-plus-sign"></i></button>
    <% end %>
  </div>
  <div class="span10">
    <% current_user.learners.each do |learner| %>
    <%= image_tag( learner.avatar.url( :medium ), :class => "img-circle" )  %>
    <h5><%= learner.name %></h5>
    <% end %>
  </div>
</div>
  <div class="clear"></div>
  <% end %> 