config/routes.rb
FastLearningCompany::Application.routes.draw do

  root                            to: 'static_pages#home'

  match '/home',                  to: 'static_pages#home'  
  match '/about',                 to: 'static_pages#about' 
  match '/calendar',              to: 'static_pages#calendar' 
  match '/terms',                 to: 'static_pages#terms' 
  match '/contact',               to: 'static_pages#contact' 

  resources :courses  
  resources :classrooms, except: [:show] do
    match ':id(.:format)',  to: 'classrooms#show', as: :page, via: :get
  end

  resources :learning_plans
  resources :products
  resources :orders

  resources  :checkout

  resources :enrollments
  
  resources :sessions, only: [:new, :create, :destroy]
  
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/profile', to: 'users#show'
  
  resources :passwords
  
  resources :pages

  resources :resources
  

  resources :companies, :path => '', :path_names => { :edit => 'account' } 
  resources :companies, :path => '', :only => [], :shallow => true do 
    resources :learners, :path => 'people', :path_names => { :edit => 'account',  :new => 'new' } 
  end

  match '*a', :to => 'errors#routing'

end

app/models/company.rb
class Company < User

  # Associations
  has_many :learners, :dependent => :destroy
  has_one  :account, :foreign_key => "accountant_id"
  
  # Callbacks
  before_create     { set_status( 'new' ) }
  after_create      :setup_account

  private
  def setup_account
    company_account = CompanyAccount.create
    account = self.build_account
    account.accountable = company_account
    self.account.save
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  load_and_authorize_resource :find_by => :id_hash

  def show
  end
  
  def edit
  end

  def update
    # Resource already loaded
    if @company.update_attributes( params[:company] )
      flash[:success] = "profil opdateret"      
      sign_in @company
      redirect_to current_user
    else
      render 'edit'
    end
  end
  
  def destroy
  end

end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/edit.html.erb
<% provide(:title, 'Rediger profil') %>

<%= render :partial => 'shared/error_messages' %>  
<%= form_for(@company, :html => {  :multipart => true, :class => "new_user"}) do |f| %>
  <%= image_tag @company.avatar.url( :medium ) %>
  <div class="clear"></div>
  <%= f.file_field :avatar %>
  <%= render :partial => 'shared/basic_user_info', :locals => { :f => f } %>  
  <div><%= f.submit "Gem ændringer", class: 'btn' %></div>
<% end %>

app/views/companies/show.html.erb
<% if current_user.role? :company %>
<div class="cl-header cl-header-inner">
  <h3 class="alt">Medarbejdere</h3>
</div>
<div class="row">
  <div class="span2">  
    <%= link_to new_company_learner_path( current_user ) do %>
    <button class="btn btn-success btn-mini pad-button"><i class="icon-white icon-plus-sign"></i></button>
    <% end %>
  </div>
  <div class="span10">
    <div class="profile">
      <ul>
	<% current_user.learners.each do |learner| %>
	<li>
	  <%= image_tag( learner.avatar.url( :medium ), :class => "profile-image")  %>
	  <h5><%= learner.name %></h5>
	</li>
    
	<% end %>
      </ul>
      </div>
  </div>
</div>
<div class="clear"></div>
<% end %> 